// Chapter 21 (Changing Case)
// Q1
var userInput = "STRING"
var allower = userInput.toLowerCase()
console.log(allower)
// Q2
var x = 'REPRESENTED'
x = x.toLowerCase()
console.log(x)
// Q3
var y = "Hello, there"
y = y.toUpperCase()
console.log(y)
// Q4
var fruit = 'APPLE'
var capFruits = fruit.toLowerCase()
console.log(capFruits)
// Q5
var arr = ['APPLE', "PINEAPPLE", "KIWI", "CHERRY"]
for (var i = 0; i <=4; i++){
    var arrcap = arr[i].toLowerCase();
    console.log(arrcap)
    alert(arrcap.toUpperCase())
}
// Q6
var str = "string"
alert(str.toUpperCase())
// Q7
var cityName = "KaRaChi"
cityName = cityName.slice(0,1).toUpperCase() + cityName.slice(1).toLowerCase()
console.log(cityName)

// Chapter 22 - 25 (Strings)
// Q1
var samewords = "captain"
console.log(samewords.slice(1,3))
// Q2
var string = "string"
var streln = string.lengthconsole.log(streln)
// Q4
var animal = "elephant"
var seg = animal.slice(2.6)
console.log(seg)
// Q5
var long_word = "sdadksfdjjfktytury4"
var long_wrd_len = long_word.length
// Q6
// 16 inedex


// Chapter 26 (Rounding Numbers)
// Q1
// Form a statement that rounds a number to the nearest integer.
var num = Math.round(3.71)
console.log(num);
// Q2
// Round up a number represented by origNum and assign it to
// roundNum, which hasn't been declared beforehand.
var origNum = 6.3456;
var roundNum = Math.ceil(origNum);
console.log(roundNum);
// Q3
// Round down a number represented by origNum and assign it to
// roundNum, which hasn't been declared beforehand.
var origNum = 7.8;
var roundNum = Math.floor(origNum);
console.log(roundNum);
// Q4
// Round a number represented by a variable and assign the result
// to a second variable that hasn't been declared beforehand.
var num = 4.563;
var result = Math.round(num);
console.log(result);
// Q5
// Round .5 to 0 and assign it to a variable that hasn't been declared beforehand.
var zero = Math.floor(0.5);
console.log(zero)
// Chapter 27 (Random Numbers)
// Q1
// Convert a random number generated by JavaScript to a number in the range 1 to 50
var rand = Math.random();
var improvedNum = (rand * 50) + 1;
console.log(improvedNum);
// Q2
// Generate a random number and assign it to a variable that hasn't been declared beforehand.
var randNum = Math.random()
console.log(randNum);
// Q3
// You have to create a dice in JavaScript with the use of pseudo- random number.
var randnum = Math.random();
var improvednum = (randnum * 6) + 1;
var dicenum = Math.floor(improvednum)
console.log(dicenum);
// Q4
// You have to create a toss (head/tail) in JavaScript with the use of pseudo-random number.
var random = Math.random();
var toss_num = (random * 2) + 1
var toss = Math.floor(toss_num);
console.log(toss) 
// Chapter 28, 29 (Converting Strings)
// Q1
// How do you convert a string to an integer in JavaScript?
// By using parseInt
// Q2
// Write a JavaScript function to convert the string "123" to an integer.
var str = parseInt("123")
console.log(str)
// Q3
// How can you convert a string containing a decimal number to a
// floating-point number in JavaScript?
// By using parseFloat
// Q4
// How can you check if a string can be successfully converted to an
// integer or decimal in JavaScript before performing the
// conversion?
// Check by using parseInt and parseFfloat
// Q5
// How can you convert a number to a string in JavaScript?
var numConvert = 123;
console.log(numConvert.toString())
// Q5
// Write a JavaScript function to convert the number 42 to a string.
var forty_two = 42;
console.log(forty_two.toString())
// Q6
// Can you convert a string representing a decimal number (e.g.,"3.14") to an integer in JavaScript? If so, how?
var decimalNum = parseFloat(3.14);
console.log(decimalNum)
// Chapter 30 (Controlling the length of decimals)
// Q1
var num = 12.3456789.toFixed(4)
var newNum = num.toString()
console.log(newNum)
// Q2

var num = 23.4567.toFixed(2).toString()
num = Number(num)
console.log(num)

// Q3
var Num = 234.456
if (num.toFixed(2).toString().length > 4){
}
// Q4

var n = 21.2345678643
console.log(n.toFixed().toString())
// Code a statement that rounds a number represented by num to 4 places, converts it to a string, and assigns it to newNum, which hasn't been declared beforehand.
// Chapter 38 (Local vs. Global Variables)
// Q1
// Write a JavaScript function that demonstrates the usage of a local variable.
function Name(firstName, lastName){
    var fullName = firstName + " " + lastName;  
    // fullName here is local variable
    console.log(fullName)
}
Name("Kulsoom", "Kazmi")
// Q2
// How can you access a global variable inside a function in JavaScript?
var theSum 
function sum(){
    theSum = 4 + 8;
    // theSum here is global variable
    console.log(theSum);    
}
sum()

// Chapter 39,40 (Switch Statement)
// Q1
// Write a JavaScript switch statement that checks the value of a
// variable and performs different actions based on different cases.
var animals = 'birds'
switch (animals){
    case "cat":
        console.log("people loves cat alot more than human being");
        break;
    case "dog":
        console.log("A loyal anima");
        break;
    case "birds":
        console.log("Love the voice of birds");
        break;
    case "insects":
        console.log("Belong to arthropos family");
        break;
}
// Q2
// Write a JavaScript switch statement that check whether cityName
// given by user check the cityName if match alert the user and
// break the statement, if not default message will be shown to user.
var cityName = prompt("Enter city name");
switch(cityName){
    case "Karachi":
        console.log("City of lights");
        break;
    case "Lahore":
        console.log("City of pujab");
        break;
    case "Multan":
        console.log("I love Multani halwa");
        break;
    default:
        console.log("Does'nt match")
}